---
title: "README"
author: "Sean Hegarty"
date: "December 21, 2014"
output: html_document
---
#Getting and Cleaning Data - Course Project

##Purpose
This repository hosts the R code and documentation files for the Data Science's track course Getting and Cleaning data. The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. Contained in this repo, you will find:
1. a tidy data set as described below, 
2. a link to a Github repository with your script for performing the analysis
3. a code book that describes the variables, the data, and any transformations or work performed to clean up the data called `CodeBook.md`. This repo explains how all of the scripts work and how they are connected.  

##The Dataset
###Human Activity Recognition Using Smartphones
One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained: 

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

Here are the data for the project: 

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 


##The Code
All data must be present in the same working directory, and un-zipped.

`run_analysis.R`: 
*Merges the training and the test sets to create one data set.
*Extracts only the measurements on the mean and standard deviation for each measurement. 
*Uses descriptive activity names to name the activities in the data set
*Appropriately labels the data set with descriptive variable names. 
*Creates a second, independent tidy data set with the average of each variable for each activity and each subject.

`run_analysis.R` can be launched in RStudio after importing the file.

## The Code Book
CodeBook.md describes the variables, the data, and any transformations or work that was performed to clean up the data.